# Generated by Django 4.1.7 on 2023-09-07 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opening_Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.CharField(choices=[('1 AM', '1 AM'), ('2 AM', '2 AM'), ('3 AM', '3 AM'), ('4 AM', '4 AM'), ('5 AM', '5 AM'), ('6 AM', '6 AM'), ('7 AM', '7 AM'), ('8 AM', '8 AM'), ('9 AM', '9 AM'), ('10 AM', '10 AM'), ('11 AM', '11 AM'), ('12 AM', '12 AM'), ('1 PM', '1 PM'), ('2 PM', '2 PM'), ('3 PM', '3 PM'), ('4 PM', '4 PM'), ('5 PM', '5 PM'), ('6 PM', '6 PM'), ('7 PM', '7 PM'), ('8 PM', '8 PM'), ('9 PM', '9 PM'), ('10 PM', '10 PM'), ('11 PM', '11 PM'), ('12 PM', '12 PM')], max_length=50, verbose_name='Closing Time')),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 9, 28, 14, 392183), verbose_name='Last Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, verbose_name='Service Name')),
                ('service_intro', models.CharField(max_length=120, verbose_name='Service Intro( max 120 characters )')),
                ('service_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Used_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Car Title')),
                ('short_intro', models.CharField(max_length=100, verbose_name='Short Intro (max 100 characters)')),
                ('card_img', models.ImageField(default='', upload_to='used_cars', verbose_name='Car Image')),
                ('price', models.IntegerField(default=0, null=True)),
                ('description', models.TextField()),
                ('model', models.CharField(max_length=50, null=True)),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2023, 9, 7, 9, 28, 14, 391183), verbose_name='Last Edited on')),
            ],
        ),
    ]
