# Generated by Django 4.1.7 on 2023-09-07 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0003_alter_opening_hours_last_modified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Service is Available'),
        ),
        migrations.AlterField(
            model_name='opening_hours',
            name='last_modified_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 9, 43, 34, 501938), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='used_car',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 9, 43, 34, 500940), verbose_name='Last Edited on'),
        ),
    ]
