# Generated by Django 4.1.7 on 2023-09-07 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0006_opening_hours_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_icon',
            field=models.ImageField(default='', upload_to='service_icons'),
        ),
        migrations.AlterField(
            model_name='opening_hours',
            name='last_modified_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 9, 49, 23, 460706), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='used_car',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 9, 49, 23, 459708), verbose_name='Last Edited on'),
        ),
    ]
