# Generated by Django 4.1.7 on 2023-09-07 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src_App', '0007_service_service_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='used_car',
            old_name='card_img',
            new_name='car_img',
        ),
        migrations.AlterField(
            model_name='opening_hours',
            name='last_modified_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 12, 41, 11, 927687), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='used_car',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 12, 41, 11, 926687), verbose_name='Last Edited on'),
        ),
    ]
